// <auto-generated />
using System;
using Cwiczenia7.Dataa;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cwiczenia7.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519192557_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cwiczenia7.Modelss.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("ComponentManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturerId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "CPU0000001",
                            ComponentManufacturerId = 1,
                            ComponentTypeId = 1,
                            Description = "8-core gaming processor",
                            Name = "Ryzen 7 7800X3D"
                        },
                        new
                        {
                            Code = "GPU0000001",
                            ComponentManufacturerId = 2,
                            ComponentTypeId = 2,
                            Description = "High-end gaming graphics card",
                            Name = "RTX 4080 Super"
                        },
                        new
                        {
                            Code = "RAM0000001",
                            ComponentManufacturerId = 3,
                            ComponentTypeId = 3,
                            Description = "DDR5 RAM module 16GB",
                            Name = "Corsair Vengeance DDR5 16GB"
                        });
                });

            modelBuilder.Entity("Cwiczenia7.Modelss.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "AMD",
                            FoundationDate = new DateTime(1969, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Advanced Micro Devices"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "NV",
                            FoundationDate = new DateTime(1993, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "COR",
                            FoundationDate = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Corsair Gaming Inc."
                        });
                });

            modelBuilder.Entity("Cwiczenia7.Modelss.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Card"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Memory"
                        });
                });

            modelBuilder.Entity("Cwiczenia7.Modelss.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast X",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Mini Pro",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 4.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 10, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Name = "Creator Station",
                            Stock = 3,
                            Warranty = 30,
                            Weight = 10.1
                        });
                });

            modelBuilder.Entity("Cwiczenia7.Modelss.PcComponent", b =>
                {
                    b.Property<int>("PcId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("nchar(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PcId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PcId = 1,
                            ComponentCode = "CPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "GPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "RAM0000001",
                            Amount = 2
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "CPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "RAM0000001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "CPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "GPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "RAM0000001",
                            Amount = 4
                        });
                });

            modelBuilder.Entity("Cwiczenia7.Modelss.Component", b =>
                {
                    b.HasOne("Cwiczenia7.Modelss.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cwiczenia7.Modelss.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("Cwiczenia7.Modelss.PcComponent", b =>
                {
                    b.HasOne("Cwiczenia7.Modelss.Component", "Component")
                        .WithMany("PcComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cwiczenia7.Modelss.Pc", "Pc")
                        .WithMany("PcComponents")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("Cwiczenia7.Modelss.Component", b =>
                {
                    b.Navigation("PcComponents");
                });

            modelBuilder.Entity("Cwiczenia7.Modelss.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Cwiczenia7.Modelss.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Cwiczenia7.Modelss.Pc", b =>
                {
                    b.Navigation("PcComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
